services:
  mobile-reverse-proxy:
    container_name: mobile-reverse-proxy
    image: nginx:latest
    ports:
      - '8443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - orchestration_net
      - public_net

networks:
  orchestration_net:
    external: true
  public_net:
    external: true
