apiVersion: v1
kind: ConfigMap
metadata:
  name: mobile-proxy-headers
  namespace: default
data:
  Host: "$host"
  X-Real-IP: "$remote_addr"
  X-Forwarded-For: "$proxy_add_x_forwarded_for"
  X-Forwarded-Proto: "https"
  X-Client-Type: "mobile"